/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProviderRouteRouteImport } from './routes/provider/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProviderIndexRouteImport } from './routes/provider/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProviderSettingsRouteImport } from './routes/provider/settings'
import { Route as ProviderOverviewRouteImport } from './routes/provider/overview'
import { Route as ProviderNoProviderRouteImport } from './routes/provider/no-provider'
import { Route as ProviderMembersRouteImport } from './routes/provider/members'
import { Route as ProviderAccountRouteImport } from './routes/provider/account'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as PublicSignUpRouteImport } from './routes/_public/sign-up'
import { Route as PublicSignInRouteImport } from './routes/_public/sign-in'
import { Route as PublicAcceptInviteTokenRouteImport } from './routes/_public/accept-invite.$token'

const ProviderRouteRoute = ProviderRouteRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderIndexRoute = ProviderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProviderRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProviderSettingsRoute = ProviderSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProviderRouteRoute,
} as any)
const ProviderOverviewRoute = ProviderOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => ProviderRouteRoute,
} as any)
const ProviderNoProviderRoute = ProviderNoProviderRouteImport.update({
  id: '/no-provider',
  path: '/no-provider',
  getParentRoute: () => ProviderRouteRoute,
} as any)
const ProviderMembersRoute = ProviderMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ProviderRouteRoute,
} as any)
const ProviderAccountRoute = ProviderAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ProviderRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicSignUpRoute = PublicSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSignInRoute = PublicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAcceptInviteTokenRoute = PublicAcceptInviteTokenRouteImport.update({
  id: '/accept-invite/$token',
  path: '/accept-invite/$token',
  getParentRoute: () => PublicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/provider': typeof ProviderRouteRouteWithChildren
  '/sign-in': typeof PublicSignInRoute
  '/sign-up': typeof PublicSignUpRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/provider/account': typeof ProviderAccountRoute
  '/provider/members': typeof ProviderMembersRoute
  '/provider/no-provider': typeof ProviderNoProviderRoute
  '/provider/overview': typeof ProviderOverviewRoute
  '/provider/settings': typeof ProviderSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/provider/': typeof ProviderIndexRoute
  '/accept-invite/$token': typeof PublicAcceptInviteTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof PublicSignInRoute
  '/sign-up': typeof PublicSignUpRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/provider/account': typeof ProviderAccountRoute
  '/provider/members': typeof ProviderMembersRoute
  '/provider/no-provider': typeof ProviderNoProviderRoute
  '/provider/overview': typeof ProviderOverviewRoute
  '/provider/settings': typeof ProviderSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/provider': typeof ProviderIndexRoute
  '/accept-invite/$token': typeof PublicAcceptInviteTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_public': typeof PublicRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/provider': typeof ProviderRouteRouteWithChildren
  '/_public/sign-in': typeof PublicSignInRoute
  '/_public/sign-up': typeof PublicSignUpRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/provider/account': typeof ProviderAccountRoute
  '/provider/members': typeof ProviderMembersRoute
  '/provider/no-provider': typeof ProviderNoProviderRoute
  '/provider/overview': typeof ProviderOverviewRoute
  '/provider/settings': typeof ProviderSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/provider/': typeof ProviderIndexRoute
  '/_public/accept-invite/$token': typeof PublicAcceptInviteTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/provider'
    | '/sign-in'
    | '/sign-up'
    | '/admin/dashboard'
    | '/admin/users'
    | '/provider/account'
    | '/provider/members'
    | '/provider/no-provider'
    | '/provider/overview'
    | '/provider/settings'
    | '/admin/'
    | '/provider/'
    | '/accept-invite/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/admin/dashboard'
    | '/admin/users'
    | '/provider/account'
    | '/provider/members'
    | '/provider/no-provider'
    | '/provider/overview'
    | '/provider/settings'
    | '/admin'
    | '/provider'
    | '/accept-invite/$token'
  id:
    | '__root__'
    | '/'
    | '/_public'
    | '/admin'
    | '/provider'
    | '/_public/sign-in'
    | '/_public/sign-up'
    | '/admin/dashboard'
    | '/admin/users'
    | '/provider/account'
    | '/provider/members'
    | '/provider/no-provider'
    | '/provider/overview'
    | '/provider/settings'
    | '/admin/'
    | '/provider/'
    | '/_public/accept-invite/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ProviderRouteRoute: typeof ProviderRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/': {
      id: '/provider/'
      path: '/'
      fullPath: '/provider/'
      preLoaderRoute: typeof ProviderIndexRouteImport
      parentRoute: typeof ProviderRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/provider/settings': {
      id: '/provider/settings'
      path: '/settings'
      fullPath: '/provider/settings'
      preLoaderRoute: typeof ProviderSettingsRouteImport
      parentRoute: typeof ProviderRouteRoute
    }
    '/provider/overview': {
      id: '/provider/overview'
      path: '/overview'
      fullPath: '/provider/overview'
      preLoaderRoute: typeof ProviderOverviewRouteImport
      parentRoute: typeof ProviderRouteRoute
    }
    '/provider/no-provider': {
      id: '/provider/no-provider'
      path: '/no-provider'
      fullPath: '/provider/no-provider'
      preLoaderRoute: typeof ProviderNoProviderRouteImport
      parentRoute: typeof ProviderRouteRoute
    }
    '/provider/members': {
      id: '/provider/members'
      path: '/members'
      fullPath: '/provider/members'
      preLoaderRoute: typeof ProviderMembersRouteImport
      parentRoute: typeof ProviderRouteRoute
    }
    '/provider/account': {
      id: '/provider/account'
      path: '/account'
      fullPath: '/provider/account'
      preLoaderRoute: typeof ProviderAccountRouteImport
      parentRoute: typeof ProviderRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/sign-up': {
      id: '/_public/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof PublicSignUpRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/sign-in': {
      id: '/_public/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof PublicSignInRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/accept-invite/$token': {
      id: '/_public/accept-invite/$token'
      path: '/accept-invite/$token'
      fullPath: '/accept-invite/$token'
      preLoaderRoute: typeof PublicAcceptInviteTokenRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicSignInRoute: typeof PublicSignInRoute
  PublicSignUpRoute: typeof PublicSignUpRoute
  PublicAcceptInviteTokenRoute: typeof PublicAcceptInviteTokenRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicSignInRoute: PublicSignInRoute,
  PublicSignUpRoute: PublicSignUpRoute,
  PublicAcceptInviteTokenRoute: PublicAcceptInviteTokenRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ProviderRouteRouteChildren {
  ProviderAccountRoute: typeof ProviderAccountRoute
  ProviderMembersRoute: typeof ProviderMembersRoute
  ProviderNoProviderRoute: typeof ProviderNoProviderRoute
  ProviderOverviewRoute: typeof ProviderOverviewRoute
  ProviderSettingsRoute: typeof ProviderSettingsRoute
  ProviderIndexRoute: typeof ProviderIndexRoute
}

const ProviderRouteRouteChildren: ProviderRouteRouteChildren = {
  ProviderAccountRoute: ProviderAccountRoute,
  ProviderMembersRoute: ProviderMembersRoute,
  ProviderNoProviderRoute: ProviderNoProviderRoute,
  ProviderOverviewRoute: ProviderOverviewRoute,
  ProviderSettingsRoute: ProviderSettingsRoute,
  ProviderIndexRoute: ProviderIndexRoute,
}

const ProviderRouteRouteWithChildren = ProviderRouteRoute._addFileChildren(
  ProviderRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ProviderRouteRoute: ProviderRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
