import { config } from "@ntizo/eslint-config/base.js";

/** @type {import("eslint").Linter.Config[]} */
export default [
  ...config,
  {
    // Generated by drizzle-kit; not ours to style.
    ignores: ["dist/**", "node_modules/**", "**/infrastructure/migrations/**"],
  },
];
